// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsryceedxuvkiebjcowa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcnljZWVkeHV2a2llYmpjb3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MDU4NjksImV4cCI6MjA2MDE4MTg2OX0.AL-l3yScQXv7bbN33vO16b2lYWl3vtLZHgEPr3Vm1D4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);